# Use postgres/postgres user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidassist_db
    ports:
      - 5432:5432